---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    helm_bin_path: /usr/local/bin/helm

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check Helm version.
      command: "{{ helm_bin_path }} version"
      changed_when: false
      register: helm_verify_version

    - name: Verify Helm's version is {{ helm_version }}.
      assert:
        that:
          - helm_version in helm_verify_version.stdout

